# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 723a659f5c3910c6a20549c92700b23e48d4de20a80b7334c292947996f63575ea1d22b4d1a9f14d8423f129d6c275e0849da80eb827a5afab72d089c04dc7d8

test:
  secret_key_base: aa3dc079ffd0020662ae973e0e0f232f849450a9468b6589490c8fbcfdf43cb7e669e37ce480898e86fb26e8ac92bc4a21ce7fc1f8d72c3cd1a22b1e5c0b5ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
